#!/bin/sh

# ##############################################################################
# #                                  ENV VARS                                  # 
# ##############################################################################

export WALLPAPER="$HOME/.config/bspwm/assets/wallpaper.jpeg"
export LOCKSCREEN_WALLPAPER="$HOME/.config/bspwm/assets/lockscreen.jpeg"

# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }
start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

# Clear cache.
rm $HOME/.cache/dunst.log
rm $HOME/.cache/fake_battery_capacity
rm -r $HOME/.cache/dunst/

# Fix cursor size.
xsetroot -xcf /usr/share/icons/volantes-cursors/cursors/left_ptr 32

# Autostart applications.

pgrep -x sxhkd > /dev/null || sxhkd &
dunst --config $HOME/.config/dunst/dunstrc &
picom --config $HOME/.config/picom/picom.conf &

# Start polkit agent.
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Setup wallpaper.
# hsetroot -fill "$WALLPAPER"
hsetroot -solid "#1C2325"

# I hate mouse drift.
xset m 0 0

# Start MPD and mpDris2
exec mpd &
exec mpDris2 &

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

bspc monitor -d 1 2 3 4 5

# rule mpv                            state=fullscreen follow=on

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

config pointer_modifier             Mod4

config window_gap                   16

config top_padding                  48
config left_padding                 0
config right_padding                0
config bottom_padding               0

config split_ratio                  0.62
config borderless_monocle           true
config gapless_monocle              true

# ##############################################################################
# #                                 MISCELLANEOUS                              #
# ##############################################################################


